config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root 'pages#index'
    resource :session, only: %i[create destroy new]
    resources :users
    resources :questions do
      resources :answers, only: %i[create destroy update edit]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]

  def index
    @pagy, @questions = pagy Question.order(created_at: :desc)
    @questions = @questions.decorate
  end

  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @pagy, @answers = pagy @question.answers.order(created_at: :desc)
    @answers = @answers.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
      flash[:success] = t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      flash[:success] = t('.success')
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = t('.success')
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question%>

<div class="card mt-3 bg-light">
  <div class="card-body">
    <%= form_with model: question do |f| %>

      <div class="mb-3 row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :title %>
        </div>

        <div class="col-sm-10">
          <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
        </div>
      </div>

      <div class="mb-3 row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :body %>
        </div>

        <div class="col-sm-10">
          <%= f.text_area :body, class: 'form-control' %>
        </div>
      </div>

      <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/questions/_question.html.erb
<article class="card mb-3 mt-3 bg-light">
    <div class="card-body">
      <h4><%= question.title %></h2>

      <section class="card-text">
        <p class="my-2">
          <%= truncate question.body, length: 100,
           omission: "......" %>
        </p>

        <time>
          <small><%= question.time_formatted %></small>
        </time>
      </section>

      <div class="btn-group">
        <%= link_to t('global.button.show'), question_path(question), class: 'btn btn-success' %> 
        <%= link_to t('global.button.edit'), edit_question_path(question), class: 'btn btn-warning' %>
        <%= link_to t('global.button.delete'), question_path(question), class: 'btn btn-danger',
          data: {method: :delete, confirm: t('global.dialog.delete')} %>
      </div>
    </div>
  </article>

app/views/questions/edit.html.erb
<%= provide :page_title, "Que\##{@question.id}#edit" %>
<% currently_at %>

<h2 class="mb-4"><%= t('.title') %></h2>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<% provide :page_title, "All Que" %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4 text-light"><%= t('.title') %></h1>

<%= link_to t('.new'), new_question_path, class: 'mb-3 btn btn-info btn-lg' %>

<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1%>

<%= render partial: 'questions/question', collection: @questions, as: :question %>

<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>

app/views/questions/new.html.erb
<%= provide :page_title, "Que#new" %>
<% currently_at %>

<h2 class="mb-4"><%= t('.title') %></h2>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<%= provide :page_title, "Que\##{@question.id}" %>
<% currently_at %>

<article class="card mt-3 bg-light">
  <div class="card-body">
    <h3 class="mb-4"><%= @question.title %></h3>
      <p><%= @question.body %></p>
      <p><%= @question.time_formatted %></p>
      <div class="btn-group">
        <%= link_to t('global.button.edit'), edit_question_path(@question), class: "btn btn-warning"%>
        <%= link_to t('global.button.delete'), question_path(@question), class: "btn btn-danger",
        data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
      </div>
  </div>
</article>
<hr class="my-3">
<h2 class="text-light"><%= t('.write_answer') %></h2>

<%= render 'shared/errors', object: @answer%>

<div class="card mt-3 bg-light">
  <div class="card-body">
    <%= form_with model: [@question,@answer] do |f| %>
      <div class="mb-3 row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :body %>
        </div>

        <div class="col-sm-10">
          <%= f.text_area :body, class: 'form-control', rows: 4 %>
        </div>
      </div>

      <%= f.submit t('global.button.submit'), class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

<hr class="my-3">
<h2 class="text-light"><%= t('.answers') if @answers.present? %></h2>

<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1%>

<%= render partial: "answers/answer", collection: @answers, as: :answer, locals:{question: @question}%>

<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1%>