config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root 'pages#index'
    resource :session, only: %i[create destroy new]
    resources :users
    resources :questions do
      resources :answers, only: %i[create destroy update edit]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end
  end
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <%= tag.div v, class: "alert alert-#{k}" %>
<% end %>

app/views/shared/_navbar.html.erb
<%= provide :navbar do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li>
            <%= nav_tab t('menu.home'), root_path,
            class: 'nav-link px-2', current_page: current_page %>
           </li>
          <li>
            <%= nav_tab t('menu.questions'), questions_path,
            class: 'nav-link px-2', current_page: current_page  %>
          </li>
        </ul>

         <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-white',
              data: {"bs-toggle": 'dropdown'} do %>
              <%= tag.div '', class: "flag #{I18n.locale}-flag mt-1" %>
              <%= t I18n.locale %>
            <% end %>
            
            <ul class="dropdown-menu">
              <% I18n.available_locales.each do |locale| %>
                <li>
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), root_path(locale: locale),
                      class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>

        <% if user_signed_in? %>
          <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
            <li>
              <%= nav_tab "#{current_user.name_or_email.capitalize}", user_path(current_user),
              class: 'nav-link px-2', current_page: current_page %>
            </li>
            <li>
              <%= nav_tab t('menu.log_out'), session_path, data:{method: :delete},
              class: 'nav-link px-2' %>
            </li>
          </ul>
        <% else %>
          <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
            <li><%= nav_tab t('menu.log_in'), new_session_path,
            class: 'nav-link px-2', current_page: current_page  %></li>
            <li><%= nav_tab t('menu.sign_up'), new_user_path,
            class: 'nav-link px-2', current_page: current_page  %></li>
          </ul>
        <% end %>

      </nav>
    </div>
  </header>
<% end %>