config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    root 'pages#index'
    resource :session, only: %i[create destroy new]
    resources :users
    resources :questions do
      resources :answers, only: %i[create destroy update edit]
    end

    namespace :admin do
      resources :users, only: %i[index create]
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question

  def create
    @answer = @question.answers.build(answer_params)
    if @answer.save
      flash[:success] = t('.success')
      redirect_to question_path(@question, anchor: "ans-#{@answer.id}")
    else
      @question = @question.decorate
      @pagy, @answers = pagy @question.answers.order(created_at: :desc)
      @answers = @answers.decorate
      render 'questions/show'
    end
  end

  def destroy
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    flash[:success] = t('.success')
    redirect_to question_path(@question)
  end

  def edit
    @answer = @question.answers.find(params[:id])
  end

  def update
    @answer = @question.answers.find(params[:id])
    if @answer.update(answer_params)
      flash[:success] = t('.success')
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.erb
<article class="card mb-3 mt-3 bg-light" id="ans-<%= answer.id%>">
    <div class="card-body">
      <section class="card-text">
        <p class="my-2">
          <%= answer.body %>
        </p>

        <time>
          <small><%= answer.time_formatted %></small>
        </time>
      </section>
      <section class="card-text mt-3">
        <div class="btn-group">
          <%= link_to t('global.button.edit'), edit_question_answer_path(question,answer),
          class: 'btn btn-warning btn-sm' %>
          <%= link_to t('global.button.delete'), question_answer_path(question,answer),
          class: 'btn btn-danger btn-sm',
          data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
        </div>
      </section>
    </div>
  </article>

app/views/answers/_form.html.erb
<div class="card mt-3 bg-light">
  <div class="card-body">
    <%= form_with model: [question,answer] do |f| %>
      <div class="mb-3 row">
        <div class="col-sm-2 col-form-label">
          <%= f.label :body %>
        </div>

        <div class="col-sm-10">
          <%= f.text_area :body, class: 'form-control', rows: 4, required: true %>
        </div>
      </div>

      <%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/answers/edit.html.erb
<%= provide :page_title, "Ans#edit" %>
<% currently_at %>

<h2><%= t('.title')%></h2>

<%= render 'form', question: @question, answer: @answer %>